package: capacity
version: '0.3.0'
author: 'rokito'
supportpage: www.rokito.de

requires:
    redaxo: '^5.2'
    packages:
        structure: '^2.0'

page:
    title: 'Capacity'
    icon: rex-icon fa-pie-chart

